name: Publish to GH Pages
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: recursive

      - name: Debug: list workspace
        run: |
          echo "=== En $GITHUB_WORKSPACE ==="
          ls -R $GITHUB_WORKSPACE

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz \
            "https://github.com/gohugoio/hugo/releases/download/v0.96.0/hugo_extended_0.96.0_Linux-64bit.tar.gz"
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo

      - name: Build site
        working-directory: ${{ github.workspace }}
        run: |
          ${RUNNER_TEMP}/hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public